apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tenant-onboarding-
  namespace: argo-workflows
spec:
  serviceAccountName: full-permissions-service-account
  entrypoint: tenant-provisioning
  arguments:
    parameters:
      - name: REPO_URL
        value: "{REPO_URL}"
      - name: AWS_REGION
        value: "{AWS_REGION}"
      - name: TENANT_ID
        value: "tenant-2" # ID of your tenant, use this patter eg. tenant-xx (tenant-10, tenant-11)
      - name: TENANT_MODEL
        value: "siloed" # Valid values are: siloed, pooled, hybrid
      - name: GIT_USER_EMAIL
        value: "workshop.user@example.com"
      - name: GIT_USERNAME
        value: "{CODECOMMIT_USER_ID}"
      - name: GIT_BRANCH
        value: "main" # Can change based on your configs
  templates:
    - name: tenant-provisioning
      steps:
        - - name: clone-repository
            templateRef:
              name: tenant-onboarding-template
              template: clone-repository
        - - name: create-tenant-infrastructure
            templateRef:
              name: tenant-onboarding-template
              template: create-tenant-infrastructure
        - - name: create-tenant-helm-release
            templateRef:
              name: tenant-onboarding-template
              template: create-tenant-helm-release
  volumeClaimTemplates:                
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  volumes:
  - name: ssh-key
    secret:
      secretName: github-ssh-key # Secret created earlier
      items:
        - key: ssh-privatekey
          path: id_rsa