{{- if .Values.deployApps -}}
{{ range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: "{{$.Chart.Name}}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion  }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
    app: {{ .name }}
spec:
  {{- if not (index $.Values .name).autoscaling.enabled }}
  replicas: {{ (index $.Values .name).replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{$.Chart.Name}}"
      app.kubernetes.io/instance: "{{ $.Release.Name }}"
      app: {{ .name }}
  template:
    metadata:
      {{- with (index $.Values .name).podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{$.Chart.Name}}"
        app.kubernetes.io/instance: "{{ $.Release.Name }}"
        app: {{ .name }}
    spec:
      {{- with (index $.Values .name).imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .name }}
      securityContext:
        {{- toYaml (index $.Values .name).podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml (index $.Values .name).securityContext | nindent 12 }}
          image: "{{ (index $.Values .name).image.repository }}:{{ (index $.Values .name).image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ (index $.Values .name).image.pullPolicy }}
          env:
            - name: TENANT_ID
              value: "{{ $.Values.tenantId }}"
          ports:
            - name: http
              containerPort: {{ (index $.Values .name).service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ .name }}
              port: http
          readinessProbe:
            httpGet:
              path: /{{ .name }}
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index $.Values .name).affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
{{ end }}